title: "TAfinder"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2324S1-CS2103T-W10-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
